version: "1"

services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: s339795
      POSTGRES_PASSWORD: FH91Ze1WDQJk6Oed
    ports:
      - "5432:5432"

  backend:
    image: backend
    ports:
      - "8080:21200"

  mediaMicroservice:
    image: media-microservice
    ports:
      - "8081:8081"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
